import os
import logging
from threading import Thread
import telegram
from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
import yt_dlp
from flask import Flask

# --- Flask Web Server (For UptimeRobot) ---
app = Flask(__name__)

@app.route('/')
def home():
    return "I am alive!"

    def run():
        port = int(os.environ.get("PORT", 8080))
            app.run(host='0.0.0.0', port=port)

            def keep_alive():
                t = Thread(target=run)
                    t.start()
                    # ---------------------------------------------

                    # Logging setup
                    logging.basicConfig(
                        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO
                        )

                        # Get Bot Token from Environment Variable
                        BOT_TOKEN = os.environ.get('BOT_TOKEN')
                        if not BOT_TOKEN:
                            logging.critical("BOT_TOKEN environment variable not found! Exiting.")
                                exit()

                                # /start command handler
                                def start(update, context):
                                    user = update.effective_user
                                        update.message.reply_html(
                                                f"Hi {user.mention_html()}!\n\nI am a Universal Video Downloader. "
                                                        f"Just send me a link to any public video."
                                                            )

                                                            # Link handler function
                                                            def handle_link(update, context):
                                                                chat_id = update.message.chat_id
                                                                    link = update.message.text

                                                                        message = context.bot.send_message(
                                                                                chat_id=chat_id, text="🔗 Got it! Starting download, please wait..."
                                                                                    )

                                                                                        # yt-dlp options for universal downloading
                                                                                            ydl_opts = {
                                                                                                    'outtmpl': f'downloads/{chat_id}_%(id)s.%(ext)s',
                                                                                                            'format': 'bestvideo[ext=mp4][height<=720]+bestaudio[ext=m4a]/best[ext=mp4]/best',
                                                                                                                    'max_filesize': 48 * 1024 * 1024,
                                                                                                                            'noplaylist': True,
                                                                                                                                    'postprocessors': [{'key': 'FFmpegVideoConvertor', 'preferedformat': 'mp4'}],
                                                                                                                                            'quiet': True,
                                                                                                                                                }

                                                                                                                                                    try:
                                                                                                                                                            if not os.path.exists('downloads'):
                                                                                                                                                                        os.makedirs('downloads')

                                                                                                                                                                                with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                                                                                                                                                                                            info = ydl.extract_info(link, download=True)
                                                                                                                                                                                                        filename = ydl.prepare_filename(info)

                                                                                                                                                                                                                context.bot.edit_message_text(
                                                                                                                                                                                                                            text="✅ Download complete! Now sending to you...",
                                                                                                                                                                                                                                        chat_id=chat_id,
                                                                                                                                                                                                                                                    message_id=message.message_id,
                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                    with open(filename, 'rb') as video_file:
                                                                                                                                                                                                                                                                                context.bot.send_video(
                                                                                                                                                                                                                                                                                                chat_id=chat_id,
                                                                                                                                                                                                                                                                                                                video=video_file,
                                                                                                                                                                                                                                                                                                                                caption=info.get('title', 'Downloaded Video'),
                                                                                                                                                                                                                                                                                                                                                supports_streaming=True
                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                            os.remove(filename)

                                                                                                                                                                                                                                                                                                                                                                                except yt_dlp.utils.DownloadError as e:
                                                                                                                                                                                                                                                                                                                                                                                        error_message = str(e).lower()
                                                                                                                                                                                                                                                                                                                                                                                                reply_text = "❌ Error: Could not download from this link. It might be private, broken, or unsupported."
                                                                                                                                                                                                                                                                                                                                                                                                        if "file is larger than the configured maximum" in error_message:
                                                                                                                                                                                                                                                                                                                                                                                                                    reply_text = "❌ Error: The video is larger than 50MB and cannot be sent due to Telegram's limits."
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                    logging.error(f"Download Error for {link}: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                            context.bot.edit_message_text(text=reply_text, chat_id=chat_id, message_id=message.message_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if 'filename' in locals() and os.path.exists(filename):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                os.remove(filename)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            logging.error(f"Unexpected error for {link}: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    context.bot.edit_message_text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                text="❌ An unknown error occurred. Please try again later.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            chat_id=chat_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        message_id=message.message_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if 'filename' in locals() and os.path.exists(filename):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    os.remove(filename)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Main function to start the bot
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        keep_alive()  # Start the web server

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            updater = Updater(BOT_TOKEN, use_context=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                dp = updater.dispatcher

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    dp.add_handler(CommandHandler("start", start))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dp.add_handler(MessageHandler(Filters.regex(r'^(http|https)'), handle_link))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            logging.info("🤖 Bot has started polling!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                updater.start_polling()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    updater.idle()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        main()