import os
import telegram
from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
import yt_dlp
import logging
from flask import Flask
from threading import Thread

# --- Flask Web Server (Bot ko UptimeRobot se zinda rakhne ke liye) ---
app = Flask(__name__)

@app.route('/')
def home():
    return "I am alive and running!"

    def run():
        # Render PORT environment variable ka istemal karta hai
            port = int(os.environ.get("PORT", 8080))
                app.run(host='0.0.0.0', port=port)

                def keep_alive():
                    t = Thread(target=run)
                        t.start()
                        # --------------------------------------------------------------------

                        # Logging setup (errors ko dekhne ke liye)
                        logging.basicConfig(
                            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO
                            )

                            # Bot token ko Environment Variable se lena hai
                            try:
                                BOT_TOKEN = os.environ['BOT_TOKEN']
                                except KeyError:
                                    logging.critical("BOT_TOKEN environment variable nahi mila! Bot band ho raha hai.")
                                        exit()

                                        def start(update, context):
                                            """User ko welcome message bhejta hai."""
                                                user = update.effective_user
                                                    update.message.reply_html(
                                                            f"Hi {user.mention_html()}!\n\nMain ek Universal Video Downloader hu. "
                                                                    f"Mujhe bas kisi bhi video ka link bhejein aur main use aapke liye download kar dunga."
                                                                        )

                                                                        def handle_link(update, context):
                                                                            """User dwara bheje gaye link ko process karta hai."""
                                                                                chat_id = update.message.chat_id
                                                                                    link = update.message.text

                                                                                        message = context.bot.send_message(
                                                                                                chat_id=chat_id, text="🔗 Link mil gaya... Download shuru kar raha hu, कृपया प्रतीक्षा करें..."
                                                                                                    )

                                                                                                        ydl_opts = {
                                                                                                                'outtmpl': f'downloads/{chat_id}_%(id)s.%(ext)s',
                                                                                                                        'format': 'bestvideo[ext=mp4][height<=720]+bestaudio[ext=m4a]/best[ext=mp4]/best',
                                                                                                                                'max_filesize': 48 * 1024 * 1024,  # 50MB se thoda kam rakhein safety ke liye
                                                                                                                                        'noplaylist': True,
                                                                                                                                                'postprocessors': [{'key': 'FFmpegVideoConvertor', 'preferedformat': 'mp4'}],
                                                                                                                                                    }

                                                                                                                                                        try:
                                                                                                                                                                # Directory banayein agar nahi hai
                                                                                                                                                                        if not os.path.exists('downloads'):
                                                                                                                                                                                    os.makedirs('downloads')

                                                                                                                                                                                            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                                                                                                                                                                                                        info = ydl.extract_info(link, download=True)
                                                                                                                                                                                                                    filename = ydl.prepare_filename(info)

                                                                                                                                                                                                                            context.bot.edit_message_text(
                                                                                                                                                                                                                                        text="✅ Download poora hua! Ab aapko bhej raha hu...",
                                                                                                                                                                                                                                                    chat_id=chat_id,
                                                                                                                                                                                                                                                                message_id=message.message_id,
                                                                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                                                                with open(filename, 'rb') as video_file:
                                                                                                                                                                                                                                                                                            context.bot.send_video(
                                                                                                                                                                                                                                                                                                            chat_id=chat_id,
                                                                                                                                                                                                                                                                                                                            video=video_file,
                                                                                                                                                                                                                                                                                                                                            caption=info.get('title', 'Downloaded Video'),
                                                                                                                                                                                                                                                                                                                                                            supports_streaming=True
                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                        # Bhejne ke baad file delete kar dein
                                                                                                                                                                                                                                                                                                                                                                                                os.remove(filename)

                                                                                                                                                                                                                                                                                                                                                                                                    except yt_dlp.utils.DownloadError as e:
                                                                                                                                                                                                                                                                                                                                                                                                            error_message = str(e)
                                                                                                                                                                                                                                                                                                                                                                                                                    if "File is larger than the configured maximum" in error_message:
                                                                                                                                                                                                                                                                                                                                                                                                                                reply_text = "❌ Error: Video 50 MB se bada hai. Telegram ki limit ke kaaran main ise nahi bhej sakta."
                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                    reply_text = "❌ Error: Is link se download nahi kar paaya. Link public hona chahiye ya unsupported ho sakta hai."
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    logging.error(f"Download Error for link {link}: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            context.bot.edit_message_text(text=reply_text, chat_id=chat_id, message_id=message.message_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if 'filename' in locals() and os.path.exists(filename):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                os.remove(filename)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            logging.error(f"An unexpected error occurred for link {link}: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    context.bot.edit_message_text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                text="❌ Ek anjaani samasya aa gayi. Kripya baad me koshish karein.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            chat_id=chat_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        message_id=message.message_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if 'filename' in locals() and os.path.exists(filename):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    os.remove(filename)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """Bot ko start karta hai."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Web server ko chalaayein taaki service sleep na ho
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    keep_alive()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        updater = Updater(BOT_TOKEN, use_context=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            dp = updater.dispatcher

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                dp.add_handler(CommandHandler("start", start))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    dp.add_handler(MessageHandler(Filters.regex(r'^(http|https)'), handle_link))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        logging.info("🤖 Bot ne polling shuru kar di hai!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            updater.start_polling()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                updater.idle()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    main()